name: LootLocker SDK Unity Test Suite 

on:
  pull_request:
    branches: # Made towards the following
      - main
    types: # Only on the following activity
      - opened
      - synchronize # Changes to the branch like new commits, ammends, etc.
      - reopened
      - unlocked
  push:
    branches: # Made towards the following
      - main

jobs:
  test:
    name: ${{ matrix.unityVersion }}-${{ matrix.testMode }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        testMode:
          - playmode
          # No tests yet, commented out for efficiency
          #- editmode
        unityVersion:
          - 2019.4.40f1
          - 2020.3.48f1
          - 2021.3.29f1
          - 2022.3.7f1
          #- 2023.1.8f1
    steps:
      - name: Checkout SDK repository
        uses: actions/checkout@v2
        with:
          repository: LootLocker/unity-sdk
          path: ./

      - name: Checkout this repository
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          path: ./tests~ # Unity ignores folders with ~ from inclusion

      - name: Switch to branch under test # If nothing specified or the current branch is main the variable will be empty and no branch switch is done
        run: cd tests~ && sudo chmod 777 branchUnderTest.sh && BRANCHUNDERTEST=$(./branchUnderTest.sh) && cd .. && git fetch --all && git checkout $BRANCHUNDERTEST

      - name: Log branches being built/tested
        run: echo "SDK BRANCH" && git branch && cd tests~ && echo "TEST BRANCH" && git branch && cd ..

      - name: Set SDK path in test repo
        run: sudo chmod 777 ./tests~/switchLootLockerDependency.sh && ./tests~/switchLootLockerDependency.sh "./tests~/" "file:../../"

      - name: Cache Libraries
        uses: actions/cache@v2
        with:
          path: tests~/Library
          key: Library-${{ matrix.unityVersion }}-${{ matrix.testMode }}
          restore-keys: Library-

      - name: Run tests ${{ matrix.unityVersion }}-${{ matrix.testMode }}
        id: tests
        uses: game-ci/unity-test-runner@v2
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          testMode: ${{ matrix.testMode }}
          checkName: ${{ matrix.unityVersion }}-${{ matrix.testMode }} Test Results
          artifactsPath: ${{ matrix.unityVersion }}-${{ matrix.testMode }}-artifacts
          projectPath: tests~/
          unityVersion: ${{ matrix.unityVersion }}
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          customParameters: -apikey ${{ secrets.LOOTLOCKER_API_KEY }} -domainkey ${{ secrets.LOOTLOCKER_DOMAIN_KEY }}

      # Commented out because as of right now it doesn't expand the test results, just repeat pass/fail
      #- uses: actions/upload-artifact@v2
      #  with:
      #    name: Test results for ${{ matrix.unityVersion }}-${{ matrix.testMode }}
      #    path: ${{ steps.tests.outputs.artifactsPath }}
